<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>MainWindow</name>
    <message>
        <location filename="SaveState_gui.py" line="491"/>
        <source>Impostazioni</source>
        <translation>Settings</translation>
    </message>
    <message>
        <source>Nascondi Log</source>
        <translation type="vanished">hide log</translation>
    </message>
    <message>
        <source>Operazione in Corso</source>
        <translation type="vanished">Operation in Progress</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="597"/>
        <source>Errore Traduzione</source>
        <translation>Translation Error</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="371"/>
        <location filename="SaveState_gui.py" line="511"/>
        <source>Ricerca in corso...</source>
        <translation>Searching...</translation>
    </message>
    <message>
        <source>Impossibile caricare il file di traduzione per l&apos;inglese ({0}).
L&apos;interfaccia rimarrà in italiano.</source>
        <translation type="vanished">Unable to upload the translation file for English ({0}).
The interface will remain in Italian.</translation>
    </message>
    <message>
        <source>Profilo &apos;{0}&apos; eliminato.</source>
        <translation type="vanished">Profile ‘{0}’ deleted.</translation>
    </message>
    <message>
        <source>Errore Configurazione</source>
        <translation type="vanished">Configuration Error</translation>
    </message>
    <message>
        <source>Impostazioni necessarie (percorso base, max backup, max dimensione sorgente) non trovate o non valide!</source>
        <translation type="vanished">Required settings (base path, max backup, max source size) not found or invalid!</translation>
    </message>
    <message>
        <source>Errore Percorso Sorgente</source>
        <translation type="vanished">Source Path Error</translation>
    </message>
    <message>
        <source>La cartella sorgente dei salvataggi non esiste o non è valida:
{0}</source>
        <translation type="vanished">The source folder of the saves does not exist or is invalid:
{0}</translation>
    </message>
    <message>
        <source>Spazio su disco insufficiente per il backup!

Spazio libero: {0:.2f} GB
Spazio minimo richiesto: {1} GB

Libera spazio sul disco di destinazione (&apos;{2}&apos;) o disabilita il controllo nelle impostazioni.</source>
        <translation type="vanished">Insufficient disk space for backup!

Free space: {0:.2f} GB
Minimum space required: {1} GB

Free up space on target disk (&apos;{2}&apos;) or disable control in settings.</translation>
    </message>
    <message>
        <source>Spazio Disco Insufficiente</source>
        <translation type="vanished">Insufficient Disk Space</translation>
    </message>
    <message>
        <source>Errore nel controllo dello spazio: il percorso di backup specificato non sembra essere valido o accessibile:
{0}</source>
        <translation type="vanished">Error checking space: the specified backup path does not appear to be valid or accessible:
{0}</translation>
    </message>
    <message>
        <source>Errore Percorso Backup</source>
        <translation type="vanished">Backup Path Error</translation>
    </message>
    <message>
        <source>Si è verificato un errore durante il controllo dello spazio libero sul disco:
{0}</source>
        <translation type="vanished">An error occurred while checking the free disk space:
{0}</translation>
    </message>
    <message>
        <source>Errore Controllo Spazio</source>
        <translation type="vanished">Space Control Error</translation>
    </message>
    <message>
        <source>Un backup o ripristino è già in corso. Attendi il completamento.</source>
        <translation type="vanished">A backup or restore is already in progress. Wait for completion.</translation>
    </message>
    <message>
        <source>Avvio backup per &apos;{0}&apos;...</source>
        <translation type="vanished">Start backup for &apos;{0}&apos;...</translation>
    </message>
    <message>
        <source>Avvio ripristino per &apos;{0}&apos;...</source>
        <translation type="vanished">Restart restoration for ‘{0}’...</translation>
    </message>
    <message>
        <source>Ripristino annullato.</source>
        <translation type="vanished">Restore cancelled.</translation>
    </message>
    <message>
        <source>Nessun backup selezionato per il ripristino.</source>
        <translation type="vanished">No backup selected for recovery.</translation>
    </message>
    <message>
        <source>Selezione backup annullata.</source>
        <translation type="vanished">Backup selection canceled.</translation>
    </message>
    <message>
        <source>Operazione terminata senza messaggio.</source>
        <translation type="vanished">Operation terminated with no message.</translation>
    </message>
    <message>
        <source>Completato: {0}</source>
        <translation type="vanished">Completed: {0}</translation>
    </message>
    <message>
        <source>ERRORE: {0}</source>
        <translation type="vanished">ERROR: {0}</translation>
    </message>
    <message>
        <source>Errore Operazione</source>
        <translation type="vanished">Operation Error</translation>
    </message>
    <message>
        <source>Creazione Collegamento</source>
        <translation type="vanished">Link Creation</translation>
    </message>
    <message>
        <source>Errore Creazione Collegamento</source>
        <translation type="vanished">Link Creation Error</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="492"/>
        <source>Nuovo Profilo Manuale</source>
        <translation>New Manual Profile</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="316"/>
        <location filename="SaveState_gui.py" line="528"/>
        <source>Console Log</source>
        <translation>Console Log</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="488"/>
        <source>SaveState - 1.3.7</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="493"/>
        <source>Gestisci Giochi Steam</source>
        <translation>Manage Steam Games</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="494"/>
        <source>Elimina Profilo</source>
        <translation>Delete Profile</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="186"/>
        <location filename="SaveState_gui.py" line="495"/>
        <source>Esegui Backup</source>
        <translation>Run Backup</translation>
    </message>
    <message>
        <source>Mostra Log</source>
        <translation type="vanished">Show Log</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="190"/>
        <location filename="SaveState_gui.py" line="496"/>
        <source>Ripristina da Backup</source>
        <translation>Restore from Backup</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="195"/>
        <location filename="SaveState_gui.py" line="497"/>
        <source>Gestisci Backup</source>
        <translation>manage backup</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="199"/>
        <location filename="SaveState_gui.py" line="498"/>
        <source>Apri Cartella Backup</source>
        <translation>Open Backup folder</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="222"/>
        <location filename="SaveState_gui.py" line="519"/>
        <source>Crea collegamento backup sul desktop</source>
        <translation>Create desktop backup shortcut</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="240"/>
        <location filename="SaveState_gui.py" line="501"/>
        <source>Profili Salvati</source>
        <translation>saved profiles</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="246"/>
        <location filename="SaveState_gui.py" line="503"/>
        <source>Azioni sul Profilo Selezionato</source>
        <translation>Profile Action</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="257"/>
        <location filename="SaveState_gui.py" line="521"/>
        <source>Crea profilo da mondo Minecraft</source>
        <translation>Create profile from Minecraft world</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="279"/>
        <location filename="SaveState_gui.py" line="505"/>
        <source>Azioni Generali</source>
        <translation>General Action</translation>
    </message>
    <message>
        <location filename="SaveState_gui.py" line="598"/>
        <source>Impossibile caricare il file di traduzione &apos;{0}&apos;. L&apos;interfaccia non cambierà.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Impossibile caricare il file di traduzione per l&apos;inglese ({0}). L&apos;interfaccia rimarrà in italiano.</source>
        <translation type="vanished">Unable to load English translation file ({0}). Interface will remain in Italian.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="64"/>
        <source>Profilo</source>
        <translation>Profile</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="122"/>
        <source>Nessun profilo creato.</source>
        <translation>No profile created.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="166"/>
        <source>Ultimo</source>
        <translation>Last</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="172"/>
        <source>Nessun backup</source>
        <translation>No backup</translation>
    </message>
</context>
<context>
    <name>MainWindowHandlers</name>
    <message>
        <source>Nascondi Log</source>
        <translation type="vanished">hide log</translation>
    </message>
    <message>
        <source>Mostra Log</source>
        <translation type="vanished">Show Log</translation>
    </message>
    <message>
        <source>Errore</source>
        <translation type="vanished">Error</translation>
    </message>
    <message>
        <source>Il percorso della cartella base dei backup non è configurato nelle impostazioni.</source>
        <translation type="vanished">The path to the backup base folder is not configured in the settings.</translation>
    </message>
    <message>
        <source>Cartella Non Trovata</source>
        <translation type="vanished">folder not found</translation>
    </message>
    <message>
        <source>La cartella dei backup specificata non esiste:
&apos;{0}&apos;

Vuoi provare a crearla?</source>
        <translation type="vanished">The specified backup folder does not exist:
&apos;{0}&apos;

Do you want to try creating it?</translation>
    </message>
    <message>
        <source>Errore Creazione</source>
        <translation type="vanished">Creation Error</translation>
    </message>
    <message>
        <source>Impossibile creare la cartella:
{0}</source>
        <translation type="vanished">Unable to create folder:
{0}</translation>
    </message>
    <message>
        <source>Errore Apertura</source>
        <translation type="vanished">Opening Error</translation>
    </message>
    <message>
        <source>Impossibile aprire la cartella:
{0}</source>
        <translation type="vanished">Unable to open folder:
{0}</translation>
    </message>
    <message>
        <source>Impossibile salvare il file delle impostazioni.</source>
        <translation type="vanished">Unable to save settings file.</translation>
    </message>
    <message>
        <source>Conferma Eliminazione</source>
        <translation type="vanished">Confirm Deletion</translation>
    </message>
    <message>
        <source>Sei sicuro di voler eliminare il profilo &apos;{0}&apos;?
(Questo non elimina i file di backup già creati).</source>
        <translation type="vanished">Are you sure you want to delete the profile &apos;{0}&apos;?
(This does not delete any backup files already created).</translation>
    </message>
    <message>
        <source>Profilo &apos;{0}&apos; eliminato.</source>
        <translation type="vanished">Profile ‘{0}’ deleted.</translation>
    </message>
    <message>
        <source>Profilo eliminato dalla memoria ma impossibile salvare le modifiche.</source>
        <translation type="vanished">Profile deleted from memory but unable to save changes.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="225"/>
        <location filename="gui_handlers.py" line="332"/>
        <location filename="gui_handlers.py" line="463"/>
        <location filename="gui_handlers.py" line="638"/>
        <source>Errore Interno</source>
        <translation>Internal Error</translation>
    </message>
    <message>
        <source>Errore Percorso Sorgente</source>
        <translation type="vanished">Source Path Error</translation>
    </message>
    <message>
        <source>La cartella sorgente dei salvataggi non esiste o non è valida:
{0}</source>
        <translation type="vanished">The source folder of the saves does not exist or is invalid:
{0}</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="42"/>
        <source>Hide Log</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="44"/>
        <source>Show Log</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="110"/>
        <location filename="gui_handlers.py" line="211"/>
        <location filename="gui_handlers.py" line="396"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="110"/>
        <source>Backup base directory not configured in settings.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="116"/>
        <source>Folder Not Found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="117"/>
        <source>The specified backup folder does not exist:
&apos;{0}&apos;

Do you want to try to create it?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="125"/>
        <source>Error Creation</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="125"/>
        <source>Unable to create folder:
{0}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="138"/>
        <source>Error Opening</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="138"/>
        <source>Unable to open folder:
{0}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="200"/>
        <source>Confirm Deletion</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="201"/>
        <source>Are you sure you want to delete the profile &apos;{0}&apos;?
(This does not delete already created backup files).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="209"/>
        <source>Profile &apos;{0}&apos; deleted.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="211"/>
        <source>Profile deleted from memory but unable to save changes.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="241"/>
        <location filename="gui_handlers.py" line="348"/>
        <source>Errore Dati Profilo</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="255"/>
        <source>Uno o più percorsi sorgente non esistono o non sono validi:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="257"/>
        <source>Errore Percorsi Sorgente</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="270"/>
        <source>Errore Configurazione</source>
        <translation>Configuration Error</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="270"/>
        <source>Impostazioni necessarie (percorso base, max backup, max dimensione sorgente) non trovate o non valide!</source>
        <translation>Required settings (base path, max backup, max source size) not found or invalid!</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="287"/>
        <source>Spazio su disco insufficiente per il backup!

Spazio libero: {0:.2f} GB
Spazio minimo richiesto: {1} GB

Libera spazio sul disco di destinazione (&apos;{2}&apos;) o disabilita il controllo nelle impostazioni.</source>
        <translation>Insufficient disk space for backup!

Free space: {0:.2f} GB
Minimum space required: {1} GB

Free up space on target disk (&apos;{2}&apos;) or disable control in settings.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="288"/>
        <source>Spazio Disco Insufficiente</source>
        <translation>Insufficient Disk Space</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="291"/>
        <source>Errore nel controllo dello spazio: il percorso di backup specificato non sembra essere valido o accessibile:
{0}</source>
        <translation>Error checking space: the specified backup path does not appear to be valid or accessible:
{0}</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="292"/>
        <source>Errore Percorso Backup</source>
        <translation>Backup Path Error</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="295"/>
        <source>Si è verificato un errore durante il controllo dello spazio libero sul disco:
{0}</source>
        <translation>An error occurred while checking the free disk space:
{0}</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="296"/>
        <source>Errore Controllo Spazio</source>
        <translation>Space Control Error</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="304"/>
        <location filename="gui_handlers.py" line="370"/>
        <source>Operazione in Corso</source>
        <translation>Operation in Progress</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="304"/>
        <source>Un backup o ripristino è già in corso. Attendi il completamento.</source>
        <translation>A backup or restore is already in progress. Wait for completion.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="308"/>
        <source>Avvio backup per &apos;{0}&apos;...</source>
        <translation>Start backup for &apos;{0}&apos;...</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="361"/>
        <source>Conferma Ripristino Finale</source>
        <translation>Confirm Final Restore</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="363"/>
        <source>ATTENZIONE!
Ripristinare &apos;{0}&apos; sovrascriverà i file nelle seguenti destinazioni:
{1}

Procedere?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="396"/>
        <source>No profile selected.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="483"/>
        <source>(Recent)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="581"/>
        <source>Path Not Found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="583"/>
        <source>Could not automatically find a path for &apos;{0}&apos;.
Please enter it manually.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="587"/>
        <source>No New Path Found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="590"/>
        <source>Automatic search did not find new paths.
Do you want to keep the current path?
&apos;{0}&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="672"/>
        <source>Manual Path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="673"/>
        <source>Enter the FULL path to the save game folder for &apos;{0}&apos;:</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="690"/>
        <source>Operation finished without message.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="690"/>
        <source>Completed: {0}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="691"/>
        <source>ERROR: {0}</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>ATTENZIONE!
Ripristinare &apos;{0}&apos; sovrascriverà i file in:
&apos;{1}&apos;

Procedere?</source>
        <translation type="vanished">WARNING!
Restoring &apos;{0}&apos; will overwrite files in:
&apos;{1}&apos;

Proceed?</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="370"/>
        <source>Un&apos;altra operazione è già in corso.</source>
        <translation>Another operation is already underway.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="373"/>
        <source>Avvio ripristino per &apos;{0}&apos;...</source>
        <translation>Restart restoration for ‘{0}’...</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="386"/>
        <source>Ripristino annullato.</source>
        <translation>Restore cancelled.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="388"/>
        <source>Nessun backup selezionato per il ripristino.</source>
        <translation>No backup selected for recovery.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="390"/>
        <source>Selezione backup annullata.</source>
        <translation>Backup selection canceled.</translation>
    </message>
    <message>
        <source>Nessun profilo selezionato.</source>
        <translation type="vanished">No profile selected.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="408"/>
        <source>Azione Fallita</source>
        <translation>Action Failed</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="408"/>
        <source>Nessun profilo selezionato per creare il collegamento.</source>
        <translation>No profile selected to create the link.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="415"/>
        <source>Creazione Collegamento</source>
        <translation>Link Creation</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="417"/>
        <source>Errore Creazione Collegamento</source>
        <translation>Link Creation Error</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="445"/>
        <source>Errore Scansione Steam</source>
        <translation>Steam Scan Error</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="445"/>
        <source>Impossibile leggere i dati di Steam:
{0}</source>
        <translation>Unable to read Steam data:
{0}</translation>
    </message>
    <message>
        <source>(Recente)</source>
        <translation type="vanished">(Recent)</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="493"/>
        <source>Trovati multipli profili Steam.
Seleziona quello corretto (di solito il più recente):</source>
        <translation>Found multiple Steam profiles.
Select the correct one (usually the most recent):</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="494"/>
        <source>Selezione Profilo Steam</source>
        <translation>Steam Profile Selection</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="502"/>
        <source>Configurazione annullata (nessun profilo Steam selezionato).</source>
        <translation>Setup cancelled (no Steam profile selected).</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="532"/>
        <source>Ricerca percorso per &apos;{0}&apos; in corso...</source>
        <translation>Path search for &apos;{0}&apos; in progress...</translation>
    </message>
    <message>
        <source>Percorso Non Trovato</source>
        <translation type="vanished">Path Not Found</translation>
    </message>
    <message>
        <source>Impossibile trovare automaticamente un percorso per &apos;{0}&apos;.
Per favore, inseriscilo manually.</source>
        <translation type="vanished">Could not automatically find a path for &apos;{0}&apos;.
Please enter manually.</translation>
    </message>
    <message>
        <source>Nessun Nuovo Percorso Trovato</source>
        <translation type="vanished">No New Routes Found</translation>
    </message>
    <message>
        <source>La ricerca automatica non ha trovato nuovi percorsi.
Vuoi mantenere il percorso attuale?
&apos;{0}&apos;</source>
        <translation type="vanished">Automatic search did not find any new routes.
Do you want to keep the current route?
&apos;{0}&apos;</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="606"/>
        <source>[ATTUALE]</source>
        <translation>[CURRENT]</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="619"/>
        <source>--- Inserisci percorso manualmente ---</source>
        <translation>--- Enter path manually ---</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="623"/>
        <source>Sono stati trovati questi percorsi potenziali per &apos;{0}&apos;.
Seleziona quello corretto (ordinati per probabilità) o scegli l&apos;inserimento manuale:</source>
        <translation>These potential paths for &apos;{0}&apos; were found.
Select the correct one (sorted by probability) or choose manual entry:</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="627"/>
        <source>Conferma Percorso Salvataggi</source>
        <translation>Confirm Save Path</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="638"/>
        <source>Errore nella selezione del percorso.</source>
        <translation>Error selecting path.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="658"/>
        <source>Profilo &apos;{0}&apos; configurato.</source>
        <translation>Profile &apos;{0}&apos; configured.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="661"/>
        <source>Profilo Configurato</source>
        <translation>Profile Configured</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="661"/>
        <source>Profilo &apos;{0}&apos; salvato con successo.</source>
        <translation>Profile &apos;{0}&apos; saved successfully.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="663"/>
        <source>Errore Salvataggio</source>
        <translation>Saving Error</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="663"/>
        <source>Impossibile salvare il file dei profili.</source>
        <translation>Unable to save profile file.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="667"/>
        <source>Configurazione profilo annullata o fallita.</source>
        <translation>Profile setup cancelled or failed.</translation>
    </message>
    <message>
        <source>Percorso Manuale</source>
        <translation type="vanished">Manual Path</translation>
    </message>
    <message>
        <source>Inserisci il percorso COMPLETO della cartella dei salvataggi per &apos;{0}&apos;:</source>
        <translation type="vanished">Enter the FULL path to the save folder for &apos;{0}&apos;:</translation>
    </message>
    <message>
        <source>Operazione terminata senza messaggio.</source>
        <translation type="vanished">Operation terminated with no message.</translation>
    </message>
    <message>
        <source>Completato: {0}</source>
        <translation type="vanished">Completed: {0}</translation>
    </message>
    <message>
        <source>ERRORE: {0}</source>
        <translation type="vanished">ERROR: {0}</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="696"/>
        <source>Errore Operazione</source>
        <translation>Operation Error</translation>
    </message>
</context>
<context>
    <name>ManageBackupsDialog</name>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="20"/>
        <source>Gestisci Backup per {0}</source>
        <translation>Manage Backup for {0}</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="27"/>
        <source>Elimina Selezionato</source>
        <translation>Delete Selected</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="34"/>
        <source>Chiudi</source>
        <translation>Close</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="42"/>
        <source>Backup esistenti per &apos;{0}&apos;:</source>
        <translation>Existing backups for &apos;{0}&apos;:</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="87"/>
        <source>No backups found.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Nessun backup trovato.</source>
        <translation type="vanished">No backups found.</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="128"/>
        <source>Conferma Eliminazione</source>
        <translation>Confirm Deletion</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="132"/>
        <source>Sei sicuro di voler eliminare PERMANENTEMENTE il file di backup:

{0}

Questa azione non può essere annullata!</source>
        <translation>Are you sure you want to PERMANENTLY delete the backup file:

{0}

This action cannot be undone!</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="144"/>
        <source>Successo</source>
        <translation>Success</translation>
    </message>
    <message>
        <location filename="dialogs/manage_backups_dialog.py" line="147"/>
        <source>Errore Eliminazione</source>
        <translation>Error Deleting</translation>
    </message>
</context>
<context>
    <name>MinecraftWorldsDialog</name>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="25"/>
        <source>Select Minecraft World</source>
        <oldsource>Seleziona Mondo Minecraft</oldsource>
        <translation type="unfinished">Select Minecraft World</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="31"/>
        <source>Select the world to create a profile for:</source>
        <oldsource>Seleziona il mondo per cui creare un profilo:</oldsource>
        <translation type="unfinished">Select the world for which to create a profile:</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="38"/>
        <source>No worlds found in the Minecraft &apos;saves&apos; folder.
Check that Minecraft Java Edition is installed correctly.</source>
        <oldsource>Nessun mondo trovato nella cartella &apos;saves&apos; di Minecraft.
Verifica che Minecraft Java Edition sia installato correttamente.</oldsource>
        <translation type="unfinished">No world found in Minecraft &apos;saves&apos; folder.
Verify that Minecraft Java Edition is installed correctly.</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="87"/>
        <source>Selection Error</source>
        <oldsource>Errore Selezione</oldsource>
        <translation type="unfinished">Error Selection</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="87"/>
        <source>Unable to retrieve the selected world&apos;s data.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Impossibile recuperare i dati del mondo selezionato.</source>
        <translation type="vanished">Unable to retrieve data from the selected world.</translation>
    </message>
</context>
<context>
    <name>ProfileCreationManager</name>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="290"/>
        <source>Errore Dipendenza</source>
        <translation type="unfinished">Dependency Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="291"/>
        <source>Le librerie &apos;winshell&apos; e &apos;pywin32&apos; sono necessarie per leggere i collegamenti (.lnk) su Windows.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>RestoreDialog</name>
    <message>
        <location filename="dialogs/restore_dialog.py" line="17"/>
        <source>Ripristina Backup per {}</source>
        <translation>Restore Backup for {}</translation>
    </message>
    <message>
        <location filename="dialogs/restore_dialog.py" line="39"/>
        <source>Nessun backup trovato per questo profilo.</source>
        <translation>No backups found for this profile.</translation>
    </message>
    <message>
        <location filename="dialogs/restore_dialog.py" line="72"/>
        <source>Ripristina Selezionato</source>
        <translation>Restore Selected</translation>
    </message>
    <message>
        <location filename="dialogs/restore_dialog.py" line="80"/>
        <source>Seleziona il backup da cui ripristinare:</source>
        <translation>Select the backup to restore from:</translation>
    </message>
</context>
<context>
    <name>SettingsDialog</name>
    <message>
        <location filename="dialogs/settings_dialog.py" line="26"/>
        <location filename="dialogs/settings_dialog.py" line="143"/>
        <source>Impostazioni Applicazione</source>
        <translation>Application Settings</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="36"/>
        <location filename="dialogs/settings_dialog.py" line="144"/>
        <source>Percorso Base Backup</source>
        <translation>Basic Backup Path</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="156"/>
        <source>Standard (Consigliato)</source>
        <translation>Standard (Recommended)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="157"/>
        <source>Massima (Più Lento)</source>
        <translation>Maximum (Slowest)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="160"/>
        <source>Nessuna (Più Veloce)</source>
        <translation>None (Fastest)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="145"/>
        <source>Dimensione Massima Sorgente per Backup</source>
        <translation>Maximum Source Size for Backup</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="146"/>
        <source>Numero Massimo Backup per Profilo</source>
        <translation>Maximum Number of Backups per Profile</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="148"/>
        <source>Compressione Backup (.zip)</source>
        <translation>Backup Compression (.zip)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="149"/>
        <source>Controllo Spazio Libero Disco</source>
        <translation>Checking Disk Free Space</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="150"/>
        <source>Abilita controllo spazio prima del backup (minimo {0} GB)</source>
        <translation>Enable space check before backup (minimum {0} GB)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="167"/>
        <source>Sfoglia...</source>
        <translation>Browse...</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="169"/>
        <source>Salva</source>
        <translation>Save</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="171"/>
        <source>Annulla</source>
        <translation>Cancel</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="185"/>
        <source>Seleziona Cartella Base per i Backup</source>
        <translation>Unable to load the translation file for English ({0}).
The interface will remain in Italian.Select Base Folder for Backups</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="213"/>
        <source>Errore Interno</source>
        <translation>Internal Error</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="213"/>
        <source>Impossibile validare il percorso.</source>
        <translation>Unable to load the translation file for English ({0}).
The interface will remain in Italian.SelectCannot validate path.ona Base Folder for Backups.</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="218"/>
        <source>Impostazioni</source>
        <translation>Settings</translation>
    </message>
</context>
<context>
    <name>SteamDialog</name>
    <message>
        <location filename="dialogs/steam_dialog.py" line="25"/>
        <source>Gestione dei giochi Steam</source>
        <oldsource>Steam Games Management</oldsource>
        <translation>Steam Game Management</translation>
    </message>
    <message>
        <source>Avvio scansione Steam...</source>
        <oldsource>Starting Steam scan...</oldsource>
        <translation type="vanished">Starting Steam Scan...</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="39"/>
        <source>Configura Profilo Selezionato</source>
        <translation>Configure Selected Profile</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="40"/>
        <source>Aggiorna elenco giochi</source>
        <translation>Update game list</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="41"/>
        <source>Chiudi</source>
        <translation>Close</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="46"/>
        <source>Giochi Steam installati:</source>
        <translation>Steam Games Installed:</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="83"/>
        <source>Nessun gioco trovato.</source>
        <translation>No games found.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="90"/>
        <source>[PROFILO ESISTENTE]</source>
        <translation>[EXISTING PROFILE]</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="157"/>
        <location filename="dialogs/steam_dialog.py" line="268"/>
        <source>Errore Interno</source>
        <translation>Internal Error</translation>
    </message>
    <message>
        <source>Impossibile trovare i dettagli per l&apos;AppID {0}.</source>
        <translation type="vanished">Unable to find details for AppID {0}.</translation>
    </message>
    <message>
        <source>(Recente)</source>
        <translation type="vanished">(Recent)</translation>
    </message>
    <message>
        <source>Selezione Profilo Steam</source>
        <translation type="vanished">Steam Profile Selection</translation>
    </message>
    <message>
        <source>Trovati multipli profili Steam.
Seleziona quello corretto (di solito il più recente):</source>
        <translation type="vanished">Found multiple Steam profiles.
Select the correct one (usually the most recent):</translation>
    </message>
    <message>
        <source>Errore nel recuperare l&apos;ID del profilo selezionato.</source>
        <translation type="vanished">Error retrieving selected profile ID.</translation>
    </message>
    <message>
        <source>Configurazione annullata (nessun profilo Steam selezionato).</source>
        <translation type="vanished">Setup cancelled (no Steam profile selected).</translation>
    </message>
    <message>
        <source>Ricerca percorso per &apos;{0}&apos; in corso...</source>
        <translation type="vanished">Path search for &apos;{0}&apos; in progress...</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="38"/>
        <source>Seleziona un gioco e clicca Configura.</source>
        <translation>Select a game and click Configure.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="77"/>
        <source>Elenco aggiornato. {0} giochi trovati.</source>
        <translation>List updated. {0} games found.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="107"/>
        <source>Errore</source>
        <translation>Error</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="107"/>
        <source>Impossibile ottenere dati del gioco selezionato.</source>
        <translation>Unable to get data for the selected game.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="158"/>
        <source>Impossibile recuperare il nome del profilo in configurazione.</source>
        <translation>Unable to retrieve profile name in configuration.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="172"/>
        <source>Percorso Non Trovato</source>
        <translation>Path Not Found</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="174"/>
        <source>Impossibile trovare automaticamente un percorso per &apos;{0}&apos;.
Per favore, inseriscilo manualmente.</source>
        <translation>Could not automatically find a path for &apos;{0}&apos;.
Please enter it manually.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="179"/>
        <source>Nessun Nuovo Percorso Trovato</source>
        <translation>No New Routes Found</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="182"/>
        <source>La ricerca automatica non ha trovato nuovi percorsi.
Vuoi mantenere il percorso attuale?
&apos;{0}&apos;</source>
        <translation>Automatic search did not find any new routes.
Do you want to keep the current route?
&apos;{0}&apos;</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="193"/>
        <source>Configurazione annullata.</source>
        <translation>Configuration cancelled.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="223"/>
        <source>[ATTUALE]</source>
        <translation>[CURRENT]</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="247"/>
        <source>--- Inserisci percorso manualmente ---</source>
        <translation>--- Enter path manually ---</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="251"/>
        <source>Sono stati trovati questi percorsi potenziali per &apos;{0}&apos;.
Seleziona quello corretto (ordinati per probabilità) o scegli l&apos;inserimento manuale:</source>
        <translation>These potential paths for &apos;{0}&apos; were found.
Select the correct one (sorted by probability) or choose manual entry:</translation>
    </message>
    <message>
        <source>Seleziona il percorso corretto per i salvataggi di &apos;{0}&apos;:</source>
        <translation type="vanished">Please select the correct path for &apos;{0}&apos; saves:</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="256"/>
        <source>Conferma Percorso Salvataggi</source>
        <translation>Confirm Save Path</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="268"/>
        <source>Errore nella selezione del percorso.</source>
        <translation>Errore nella selezione del percorso.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="271"/>
        <source>Configuration cancelled.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="279"/>
        <source>Profilo &apos;{0}&apos; configurato.</source>
        <translation>Profile &apos;{0}&apos; configured.</translation>
    </message>
    <message>
        <source>Profilo Configurato</source>
        <translation type="vanished">Profile Configured</translation>
    </message>
    <message>
        <source>Profilo &apos;{0}&apos; salvato con successo.</source>
        <translation type="vanished">Profile &apos;{0}&apos; saved successfully.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="283"/>
        <source>Errore Salvataggio</source>
        <translation>Saving Error</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="284"/>
        <source>Impossibile salvare il file dei profili.</source>
        <translation>Unable to save profile file.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="285"/>
        <source>Errore durante il salvataggio dei profili.</source>
        <translation>Error saving profiles.</translation>
    </message>
    <message>
        <source>Configurazione annullata o fallita.</source>
        <translation type="vanished">Setup cancelled or failed.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="307"/>
        <location filename="dialogs/steam_dialog.py" line="332"/>
        <source>Errore Percorso</source>
        <translation>Path Error</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="308"/>
        <source>Il percorso specificato non esiste o non è una cartella valida.</source>
        <translation>The specified path does not exist or is not a valid folder.</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="318"/>
        <source>Percorso Manuale</source>
        <translation>Manual Path</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="319"/>
        <source>Inserisci il percorso COMPLETO dei salvataggi per &apos;{0}&apos;:</source>
        <translation>Enter the FULL path to your saves for &apos;{0}&apos;:</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="332"/>
        <source>Il percorso non può essere vuoto.</source>
        <translation>The path cannot be empty.</translation>
    </message>
</context>
<context>
    <name>mw</name>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="51"/>
        <location filename="gui_components/profile_creation_manager.py" line="65"/>
        <location filename="gui_components/profile_creation_manager.py" line="75"/>
        <location filename="gui_components/profile_creation_manager.py" line="219"/>
        <location filename="gui_components/profile_creation_manager.py" line="667"/>
        <source>Errore Percorso</source>
        <translation>Path Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="51"/>
        <location filename="gui_components/profile_creation_manager.py" line="667"/>
        <source>Il percorso non può essere vuoto.</source>
        <translation>The path cannot be empty.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="67"/>
        <source>Non è possibile usare una radice del drive (&apos;{0}&apos;) come cartella dei salvataggi per &apos;{1}&apos;.
Per favore, scegli o crea una sottocartella specifica.</source>
        <translation>Cannot use a root drive (&apos;{0}&apos;) as a save folder for &apos;{1}&apos;.
Please choose or create a specific subfolder.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="76"/>
        <source>Il percorso specificato non esiste o non è una cartella valida:
&apos;{0}&apos;</source>
        <translation>The specified path does not exist or is not a valid folder:
&apos;{0}&apos;</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="90"/>
        <source>Nuovo Profilo</source>
        <translation>New Profile</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="90"/>
        <source>Inserisci un nome per il nuovo profilo:</source>
        <translation>Enter a name for the new profile:</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="98"/>
        <location filename="gui_components/profile_creation_manager.py" line="213"/>
        <location filename="gui_components/profile_creation_manager.py" line="389"/>
        <location filename="gui_components/profile_creation_manager.py" line="470"/>
        <source>Errore Nome Profilo</source>
        <translation>Profile Name Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="99"/>
        <source>Il nome del profilo (&apos;{0}&apos;) contiene caratteri non validi o è vuoto dopo la pulizia.</source>
        <translation>The profile name (&apos;{0}&apos;) contains invalid characters or is empty after cleanup.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="104"/>
        <location filename="gui_components/profile_creation_manager.py" line="133"/>
        <location filename="gui_components/profile_creation_manager.py" line="241"/>
        <location filename="gui_components/profile_creation_manager.py" line="690"/>
        <source>Errore</source>
        <translation>Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="104"/>
        <source>Un profilo chiamato &apos;{0}&apos; esiste già.</source>
        <translation>A profile called &apos;{0}&apos; already exists.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="108"/>
        <source>Ora inserisci il percorso COMPLETO per i salvataggi del profilo:
&apos;{0}&apos;</source>
        <translation>Now enter the FULL path to your profile saves:
&apos;{0}&apos;</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="109"/>
        <source>Percorso Salvataggi</source>
        <translation>Save Path</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="129"/>
        <source>Successo</source>
        <translation>Success</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="129"/>
        <source>Profilo &apos;{0}&apos; creato e salvato.</source>
        <translation>Profile &apos;{0}&apos; created and saved.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="130"/>
        <location filename="gui_components/profile_creation_manager.py" line="239"/>
        <location filename="gui_components/profile_creation_manager.py" line="688"/>
        <source>Profilo &apos;{0}&apos; creato.</source>
        <translation>Profile &apos;{0}&apos; created.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="133"/>
        <location filename="gui_components/profile_creation_manager.py" line="690"/>
        <source>Impossibile salvare il file dei profili.</source>
        <translation>Unable to save profile file.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="154"/>
        <source>Ricerca cartella salvataggi Minecraft...</source>
        <translation>minecraft save folders search...</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="161"/>
        <location filename="gui_components/profile_creation_manager.py" line="178"/>
        <source>Errore Minecraft</source>
        <translation>Minecraft Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="161"/>
        <source>Errore imprevisto durante la ricerca della cartella Minecraft.</source>
        <translation>Unexpected error when searching minecraft folder.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="162"/>
        <source>Errore ricerca Minecraft.</source>
        <translation>Minecraft search error.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="167"/>
        <source>Cartella Non Trovata</source>
        <translation>folder not found</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="168"/>
        <source>Impossibile trovare la cartella dei salvataggi standard di Minecraft (.minecraft/saves).
Assicurati che Minecraft Java Edition sia installato.</source>
        <translation>Unable to find the standard Minecraft saves folder (.minecraft/saves).
Make sure Minecraft Java Edition is installed.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="169"/>
        <source>Cartella Minecraft non trovata.</source>
        <translation>Minecraft folder not found.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="172"/>
        <source>Lettura mondi Minecraft...</source>
        <translation>Reading Minecraft worlds...</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="178"/>
        <source>Errore imprevisto durante la lettura dei mondi Minecraft.</source>
        <translation>Unexpected error while reading Minecraft worlds.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="179"/>
        <source>Errore lettura mondi Minecraft.</source>
        <translation>Minecraft worlds read error.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="184"/>
        <source>Nessun Mondo Trovato</source>
        <translation>No World Found</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="185"/>
        <source>Nessun mondo trovato nella cartella:
{0}</source>
        <translation>No world found in the folder:
{0}</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="186"/>
        <source>Nessun mondo Minecraft trovato.</source>
        <translation>No Minecraft worlds found.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="193"/>
        <source>Errore Interfaccia</source>
        <translation>Interface Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="193"/>
        <source>Impossibile creare la finestra di selezione dei mondi.</source>
        <translation>Unable to create the worlds selection window.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="656"/>
        <source>Internal error during result handling.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="662"/>
        <source>Insert the FULL path for the profile&apos;s saves:
&apos;{0}&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <source>Pronto.</source>
        <translation type="vanished">Ready.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="206"/>
        <location filename="gui_components/profile_creation_manager.py" line="382"/>
        <location filename="gui_components/profile_creation_manager.py" line="424"/>
        <source>Errore Interno</source>
        <translation>Internal Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="206"/>
        <source>Nome del mondo selezionato non valido.</source>
        <translation>Name of selected world invalid.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="214"/>
        <source>Il nome del mondo (&apos;{0}&apos;) contiene caratteri non validi o è vuoto dopo la pulizia.</source>
        <translation>The world name (&apos;{0}&apos;) contains invalid characters or is empty after cleanup.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="219"/>
        <source>Il percorso del mondo selezionato (&apos;{0}&apos;) non è valido.</source>
        <translation>The selected world path (&apos;{0}&apos;) is invalid.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="225"/>
        <location filename="gui_components/profile_creation_manager.py" line="394"/>
        <location filename="gui_components/profile_creation_manager.py" line="475"/>
        <source>Profilo Esistente</source>
        <translation>Existing Profile</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="226"/>
        <source>Un profilo chiamato &apos;{0}&apos; esiste già.
Scegli un altro mondo o rinomina il profilo esistente.</source>
        <translation>A profile named &apos;{0}&apos; already exists.
Choose another world or rename the existing profile.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="237"/>
        <location filename="gui_components/profile_creation_manager.py" line="687"/>
        <source>Profilo Creato</source>
        <translation>Profile Created</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="238"/>
        <source>Profilo &apos;{0}&apos; creato con successo per il mondo Minecraft.</source>
        <translation>&apos;{0}&apos; profile successfully created for the Minecraft world.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="241"/>
        <source>Impossibile salvare il file dei profili dopo aver aggiunto &apos;{0}&apos;.</source>
        <translation>Unable to save profile file after adding &apos;{0}&apos;.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="245"/>
        <source>Selezione mondo annullata o fallita.</source>
        <translation>World selection canceled or failed.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="248"/>
        <source>Selezione mondo annullata.</source>
        <translation>World selection canceled.</translation>
    </message>
    <message>
        <source>Errore Dipendenza</source>
        <translation type="vanished">Dependency Error</translation>
    </message>
    <message>
        <source>La libreria &apos;winshell&apos; necessaria non è installata.</source>
        <translation type="vanished">The required &apos;winshell&apos; library is not installed.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="323"/>
        <location filename="gui_components/profile_creation_manager.py" line="344"/>
        <source>Errore Collegamento</source>
        <translation>Link Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="324"/>
        <source>Impossibile risolvere il percorso del collegamento o il file/cartella di destinazione non esiste:
&apos;{0}&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="344"/>
        <source>Impossibile leggere il file .lnk:
{0}</source>
        <translation>Cannot read .lnk file:
{0}</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="382"/>
        <source>Dati del profilo selezionato non validi.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="390"/>
        <source>Impossibile generare un nome profilo valido per &apos;{0}&apos;.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="395"/>
        <source>Un profilo chiamato &apos;{0}&apos; esiste già. Sovrascriverlo?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="424"/>
        <source>Impossibile salvare il profilo, nessun percorso valido disponibile.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="437"/>
        <source>Profilo &apos;{0}&apos; creato/aggiornato.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="440"/>
        <source>Errore Salvataggio</source>
        <translation type="unfinished">Saving Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="442"/>
        <source>Impossibile salvare il file dei profili dopo aver aggiunto/modificato &apos;{0}&apos;. Le modifiche potrebbero essere andate perse.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="453"/>
        <source>Rilevato Emulatore ({0})</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="454"/>
        <source>Rilevato collegamento a {0}, ma nessun profilo trovato nella sua cartella standard.
Verifica la posizione dei salvataggi dell&apos;emulatore.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="471"/>
        <source>Impossibile generare un nome profilo valido dal collegamento trascinato.</source>
        <translation>Unable to generate a valid profile name from the dragged link.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="475"/>
        <source>Profilo &apos;{0}&apos; esiste già.</source>
        <translation>Profile &apos;{0}&apos; already exists.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="480"/>
        <source>Operazione in Corso</source>
        <translation>Operation in Progress</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="480"/>
        <source>Un&apos;altra ricerca di percorso è già in corso. Attendi.</source>
        <translation>Another route search is already in progress. Hold.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="484"/>
        <source>Ricerca percorso per &apos;{0}&apos; in corso...</source>
        <translation>Path search for &apos;{0}&apos; in progress...</translation>
    </message>
    <message>
        <source>Ricerca percorso completata.</source>
        <translation type="vanished">Path search completed.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="556"/>
        <source>Errore sconosciuto durante la ricerca.</source>
        <translation>Unknown error during search.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="558"/>
        <source>Errore Ricerca Percorso</source>
        <translation>Path Search Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="560"/>
        <source>Ricerca interrotta.</source>
        <translation>Search aborted.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="573"/>
        <source>Conferma Percorso Automatico</source>
        <translation>Confirm Automatic Route</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="575"/>
        <source>È stato rilevato questo percorso:

{0}

Vuoi usarlo per il profilo &apos;{1}&apos;?</source>
        <translation>This path was detected:

{0}

Do you want to use it for profile &apos;{1}&apos;?</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="399"/>
        <location filename="gui_components/profile_creation_manager.py" line="584"/>
        <location filename="gui_components/profile_creation_manager.py" line="647"/>
        <location filename="gui_components/profile_creation_manager.py" line="671"/>
        <source>Creazione profilo annullata.</source>
        <translation>Profile creation cancelled.</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="196"/>
        <source>Ready.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="549"/>
        <source>Path search completed.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="616"/>
        <source>[Inserisci Manualmente...]</source>
        <translation>[Insert Manually...]</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="625"/>
        <source>Conferma Percorso Salvataggi</source>
        <translation>Confirm Save Path</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="626"/>
        <source>Sono stati trovati questi percorsi potenziali per &apos;{0}&apos;.
Seleziona quello corretto (ordinati per probabilità) o scegli l&apos;inserimento manuale:</source>
        <translation>These potential paths for &apos;{0}&apos; were found.
Select the correct one (sorted by probability) or choose manual entry:</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="652"/>
        <source>Percorso Non Rilevato</source>
        <translation>Path Not Detected</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="652"/>
        <source>Impossibile rilevare automaticamente il percorso dei salvataggi per &apos;{0}&apos;.
Per favore, inseriscilo manualmente.</source>
        <translation>Unable to automatically detect save path for &apos;{0}&apos;.
Please enter it manually.</translation>
    </message>
    <message>
        <source>Errore interno durante la gestione dei risultati.</source>
        <translation type="vanished">Internal error while handling results.</translation>
    </message>
    <message>
        <source>Inserisci il percorso COMPLETO per i salvataggi del profilo:
&apos;{0}&apos;</source>
        <translation type="vanished">Enter the FULL path for profile saves:
&apos;{0}&apos;</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="663"/>
        <source>Percorso Salvataggi Manuale</source>
        <translation>Manual Save Path</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="668"/>
        <source>Creazione profilo annullata (percorso vuoto).</source>
        <translation>Profile creation cancelled (empty path).</translation>
    </message>
    <message>
        <location filename="gui_components/profile_creation_manager.py" line="687"/>
        <source>Profilo &apos;{0}&apos; creato con successo.</source>
        <translation>Profile &apos;{0}&apos; successfully created.</translation>
    </message>
</context>
<context>
    <name>self.main_window</name>
    <message>
        <source>Profilo</source>
        <translation type="vanished">Profile</translation>
    </message>
    <message>
        <source>Nessun profilo creato.</source>
        <translation type="vanished">No profile created.</translation>
    </message>
    <message>
        <source>Ultimo</source>
        <translation type="vanished">Last</translation>
    </message>
    <message>
        <source>Nessun backup</source>
        <translation type="vanished">No backup</translation>
    </message>
    <message>
        <location filename="gui_components/theme_manager.py" line="85"/>
        <source>Passa al tema scuro</source>
        <translation>switch to dark theme</translation>
    </message>
    <message>
        <location filename="gui_components/theme_manager.py" line="97"/>
        <source>Passa al tema chiaro</source>
        <translation>Switch to light theme</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="176"/>
        <location filename="gui_components/profile_list_manager.py" line="242"/>
        <source>Rimuovi dai preferiti</source>
        <translation>Remove from favorites</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="179"/>
        <location filename="gui_components/profile_list_manager.py" line="245"/>
        <source>Aggiungi ai preferiti</source>
        <translation>Add to favorites</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="181"/>
        <location filename="gui_components/profile_list_manager.py" line="248"/>
        <source>Aggiungi/Rimuovi preferito</source>
        <translation>Add/Remove Favorite</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="258"/>
        <location filename="gui_components/theme_manager.py" line="128"/>
        <source>Errore</source>
        <translation>Error</translation>
    </message>
    <message>
        <location filename="gui_components/profile_list_manager.py" line="259"/>
        <source>Impossibile salvare lo stato preferito per &apos;{0}&apos;.</source>
        <translation>Unable to save preferred state for &apos;{0}&apos;.</translation>
    </message>
    <message>
        <location filename="gui_components/theme_manager.py" line="129"/>
        <source>Impossibile salvare l&apos;impostazione del tema.</source>
        <translation>Unable to save theme settings.</translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="183"/>
        <source>Settings saved.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="186"/>
        <source>Save Error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="gui_handlers.py" line="187"/>
        <source>Unable to save settings.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
