<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>MainWindow</name>
    <message>
        <source>Gestione Backup Salvataggi</source>
        <translation type="vanished">Backup Management Saves</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="331"/>
        <source>Profilo</source>
        <translation>Profile</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="331"/>
        <source>Info Backup</source>
        <translation>Info Backup</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="332"/>
        <source>Impostazioni</source>
        <translation>Settings</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="351"/>
        <source>Passa al tema scuro</source>
        <translation>switch to dark theme</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="353"/>
        <source>Passa al tema chiaro</source>
        <translation>switch to the clear theme</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="374"/>
        <source>Nascondi Log</source>
        <translation>hide log</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="430"/>
        <source>Ricerca cartella salvataggi Minecraft...</source>
        <translation>minecraft save folders search...</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="439"/>
        <location filename="game_saver_gui.py" line="458"/>
        <source>Errore Minecraft</source>
        <translation>Minecraft Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="439"/>
        <source>Errore imprevisto durante la ricerca della cartella Minecraft.</source>
        <translation>Unexpected error when searching minecraft folder.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="440"/>
        <source>Errore ricerca Minecraft.</source>
        <translation>Minecraft search error.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="446"/>
        <source>Cartella Non Trovata</source>
        <translation>folder not found</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="447"/>
        <source>Impossibile trovare la cartella dei salvataggi standard di Minecraft (.minecraft/saves).
Assicurati che Minecraft Java Edition sia installato.</source>
        <translation>Unable to find the standard Minecraft saves folder (.minecraft/saves).
Make sure Minecraft Java Edition is installed.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="448"/>
        <source>Cartella Minecraft non trovata.</source>
        <translation>Minecraft folder not found.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="452"/>
        <source>Lettura mondi Minecraft...</source>
        <translation>Reading Minecraft worlds...</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="458"/>
        <source>Errore imprevisto durante la lettura dei mondi Minecraft.</source>
        <translation>Unexpected error while reading Minecraft worlds.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="459"/>
        <source>Errore lettura mondi Minecraft.</source>
        <translation>Minecraft worlds read error.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="465"/>
        <source>Nessun Mondo Trovato</source>
        <translation>No World Found</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="466"/>
        <source>Nessun mondo trovato nella cartella:
{0}</source>
        <translation>No world found in the folder:
{0}</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="467"/>
        <source>Nessun mondo Minecraft trovato.</source>
        <translation>No Minecraft worlds found.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="475"/>
        <source>Errore Interfaccia</source>
        <translation>Interface Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="475"/>
        <source>Impossibile creare la finestra di selezione dei mondi.</source>
        <translation>Unable to create the worlds selection window.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="478"/>
        <source>Pronto.</source>
        <translation>Ready.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="491"/>
        <source>Errore Interno</source>
        <translation>Internal Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="491"/>
        <source>Nome del mondo selezionato non valido.</source>
        <translation>Name of selected world invalid.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="496"/>
        <location filename="game_saver_gui.py" line="1270"/>
        <source>Errore Percorso</source>
        <translation>Path Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="496"/>
        <source>Il percorso del mondo selezionato (&apos;{0}&apos;) non è valido.</source>
        <translation>The selected world path (&apos;{0}&apos;) is invalid.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="504"/>
        <location filename="game_saver_gui.py" line="596"/>
        <source>Profilo Esistente</source>
        <translation>Existing Profile</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="505"/>
        <source>Un profilo chiamato &apos;{0}&apos; esiste già.
Scegli un altro mondo o rinomina il profilo esistente.</source>
        <translation>A profile named &apos;{0}&apos; already exists.
Choose another world or rename the existing profile.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="515"/>
        <location filename="game_saver_gui.py" line="1292"/>
        <source>Profilo Creato</source>
        <translation>Profile Created</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="516"/>
        <source>Profilo &apos;{0}&apos; creato con successo per il mondo Minecraft.</source>
        <translation>&apos;{0}&apos; profile successfully created for the Minecraft world.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="517"/>
        <location filename="game_saver_gui.py" line="1293"/>
        <source>Profilo &apos;{0}&apos; creato.</source>
        <translation>Profile &apos;{0}&apos; created.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="520"/>
        <location filename="game_saver_gui.py" line="1296"/>
        <source>Errore</source>
        <translation>Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="520"/>
        <source>Impossibile salvare il file dei profili dopo aver aggiunto &apos;{0}&apos;.</source>
        <translation>Unable to save profile file after adding &apos;{0}&apos;.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="526"/>
        <source>Selezione mondo annullata o fallita.</source>
        <translation>World selection canceled or failed.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="530"/>
        <source>Selezione mondo annullata.</source>
        <translation>World selection canceled.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="584"/>
        <source>Errore Collegamento</source>
        <translation>Link Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="584"/>
        <source>Impossibile leggere il file .lnk:
{0}</source>
        <translation>Cannot read .lnk file:
{0}</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="596"/>
        <source>Profilo &apos;{0}&apos; esiste già.</source>
        <translation>Profilo &apos;{0}&apos; esiste già.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="603"/>
        <location filename="game_saver_gui.py" line="1041"/>
        <source>Operazione in Corso</source>
        <translation>Operation in Progress</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="603"/>
        <source>Un&apos;altra ricerca di percorso è già in corso. Attendi.</source>
        <translation>Another route search is already in progress. Hold.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="608"/>
        <source>Ricerca percorso per &apos;{0}&apos; in corso...</source>
        <translation>Path search for &apos;{0}&apos; in progress...</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="635"/>
        <source>File Ignorato</source>
        <translation>File Ignored</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="635"/>
        <source>Per favore, trascina un collegamento (.lnk) a un gioco.</source>
        <translation>Please drag a link (.lnk) to a game.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="736"/>
        <source>Ultimo</source>
        <translation>Last</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="812"/>
        <source>Errore Traduzione</source>
        <translation>Translation Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="814"/>
        <source>Impossibile caricare il file di traduzione per l&apos;inglese ({0}).
L&apos;interfaccia rimarrà in italiano.</source>
        <translation>Unable to upload the translation file for English ({0}).
The interface will remain in Italian.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="948"/>
        <source>Profilo &apos;{0}&apos; eliminato.</source>
        <translation>Profile ‘{0}’ deleted.</translation>
    </message>
    <message>
        <source>Impossibile caricare il file di traduzione per l&apos;inglese (game_saver_en.qm).
L&apos;interfaccia rimarrà in italiano.</source>
        <translation type="vanished">Unable to load the translation file for English (game_saver_en.qm).
The interface will remain in Italian.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="992"/>
        <source>Errore Configurazione</source>
        <translation>Configuration Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="992"/>
        <source>Impostazioni necessarie (percorso base, max backup, max dimensione sorgente) non trovate o non valide!</source>
        <translation>Required settings (base path, max backup, max source size) not found or invalid!</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="995"/>
        <source>Errore Percorso Sorgente</source>
        <translation>Source Path Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="995"/>
        <source>La cartella sorgente dei salvataggi non esiste o non è valida:
{0}</source>
        <translation>The source folder of the saves does not exist or is invalid:
{0}</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1017"/>
        <source>Spazio su disco insufficiente per il backup!

Spazio libero: {0:.2f} GB
Spazio minimo richiesto: {1} GB

Libera spazio sul disco di destinazione (&apos;{2}&apos;) o disabilita il controllo nelle impostazioni.</source>
        <translation>Insufficient disk space for backup!

Free space: {0:.2f} GB
Minimum space required: {1} GB

Free up space on target disk (&apos;{2}&apos;) or disable control in settings.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1018"/>
        <source>Spazio Disco Insufficiente</source>
        <translation>Insufficient Disk Space</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1023"/>
        <source>Errore nel controllo dello spazio: il percorso di backup specificato non sembra essere valido o accessibile:
{0}</source>
        <translation>Error checking space: the specified backup path does not appear to be valid or accessible:
{0}</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1024"/>
        <source>Errore Percorso Backup</source>
        <translation>Backup Path Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1028"/>
        <source>Si è verificato un errore durante il controllo dello spazio libero sul disco:
{0}</source>
        <translation>An error occurred while checking the free disk space:
{0}</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1029"/>
        <source>Errore Controllo Spazio</source>
        <translation>Space Control Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1041"/>
        <source>Un backup o ripristino è già in corso. Attendi il completamento.</source>
        <translation>A backup or restore is already in progress. Wait for completion.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1044"/>
        <source>Avvio backup per &apos;{0}&apos;...</source>
        <translation>Start backup for &apos;{0}&apos;...</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1120"/>
        <source>Avvio ripristino per &apos;{0}&apos;...</source>
        <translation>Restart restoration for ‘{0}’...</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1126"/>
        <source>Ripristino annullato.</source>
        <translation>Restore cancelled.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1127"/>
        <source>Nessun backup selezionato per il ripristino.</source>
        <translation>No backup selected for recovery.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1128"/>
        <source>Selezione backup annullata.</source>
        <translation>Backup selection canceled.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1141"/>
        <source>Operazione terminata senza messaggio.</source>
        <translation>Operation terminated with no message.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1141"/>
        <source>Completato: {0}</source>
        <translation>Completed: {0}</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1142"/>
        <source>ERRORE: {0}</source>
        <translation>ERROR: {0}</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1145"/>
        <source>Errore Operazione</source>
        <translation>Operation Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1161"/>
        <source>Ricerca percorso completata.</source>
        <translation>Path search completed.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1172"/>
        <source>Errore sconosciuto durante la ricerca.</source>
        <translation>Unknown error during search.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1175"/>
        <source>Errore Ricerca Percorso</source>
        <translation>Path Search Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1178"/>
        <source>Ricerca interrotta.</source>
        <translation>Search aborted.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1192"/>
        <source>Conferma Percorso Automatico</source>
        <translation>Automatic Route Confirmation</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1193"/>
        <source>È stato rilevato questo percorso:

{0}

Vuoi usarlo per il profilo &apos;{1}&apos;?</source>
        <translation>This path was detected:

{0}

Do you want to use it for profile &apos;{1}&apos;?</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1202"/>
        <location filename="game_saver_gui.py" line="1248"/>
        <location filename="game_saver_gui.py" line="1274"/>
        <source>Creazione profilo annullata.</source>
        <translation>Profile creation cancelled.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1232"/>
        <location filename="game_saver_gui.py" line="1242"/>
        <source>[Inserisci Manualmente...]</source>
        <translation>[Insert Manually...]</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1234"/>
        <source>Conferma Percorso Salvataggi</source>
        <translation>Confirm Save Path</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1235"/>
        <source>Sono stati trovati questi percorsi potenziali per &apos;{0}&apos;.
Seleziona quello corretto o scegli l&apos;inserimento manuale:</source>
        <translation>These potential paths were found for &apos;{0}&apos;.
Select the correct one or choose manual entry:</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1253"/>
        <source>Percorso Non Rilevato</source>
        <translation>Path Not Detected</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1253"/>
        <source>Impossibile rilevare automaticamente il percorso dei salvataggi per &apos;{0}&apos;.
Per favore, inseriscilo manualmente.</source>
        <translation>Unable to automatically detect save path for &apos;{0}&apos;.
Please enter it manually.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1257"/>
        <source>Errore interno durante la gestione dei risultati.</source>
        <translation>Errore interno durante la gestione dei risultati.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1262"/>
        <source>Inserisci il percorso COMPLETO per i salvataggi del profilo:
&apos;{0}&apos;</source>
        <translation>Enter the FULL path for profile saves:
&apos;{0}&apos;</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1263"/>
        <source>Percorso Salvataggi Manuale</source>
        <translation>Manual Save Path</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1270"/>
        <source>Il percorso non può essere vuoto.</source>
        <translation>Il percorso non può essere vuoto.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1271"/>
        <source>Creazione profilo annullata (percorso vuoto).</source>
        <translation>Creazione profilo annullata (percorso vuoto).</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1292"/>
        <source>Profilo &apos;{0}&apos; creato con successo.</source>
        <translation>Profile &apos;{0}&apos; successfully created.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1296"/>
        <source>Impossibile salvare il file dei profili.</source>
        <translation>Unable to save profile file.</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1322"/>
        <source>Creazione Collegamento</source>
        <translation>Link Creation</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="1324"/>
        <source>Errore Creazione Collegamento</source>
        <translation>Link Creation Error</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="333"/>
        <source>Nuovo Profilo Manuale</source>
        <translation>New Manual Profile</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="271"/>
        <source>Console Log</source>
        <translation>Console Log</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="334"/>
        <source>Gestisci Giochi Steam</source>
        <translation>Manage Steam Games</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="335"/>
        <source>Elimina Profilo</source>
        <translation>Delete Profile</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="141"/>
        <location filename="game_saver_gui.py" line="336"/>
        <source>Esegui Backup</source>
        <translation>Run Backup</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="99"/>
        <location filename="game_saver_gui.py" line="376"/>
        <source>Mostra Log</source>
        <translation>Show Log</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="145"/>
        <location filename="game_saver_gui.py" line="337"/>
        <source>Ripristina da Backup</source>
        <translation>Restore from Backup</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="150"/>
        <location filename="game_saver_gui.py" line="338"/>
        <source>Gestisci Backup</source>
        <translation>manage backup</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="154"/>
        <location filename="game_saver_gui.py" line="339"/>
        <source>Apri Cartella Backup</source>
        <translation>Open Backup folder</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="177"/>
        <source>Crea collegamento backup sul desktop</source>
        <translation>Create desktop backup shortcut</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="195"/>
        <location filename="game_saver_gui.py" line="342"/>
        <source>Profili Salvati</source>
        <translation>saved profiles</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="201"/>
        <location filename="game_saver_gui.py" line="344"/>
        <source>Azioni sul Profilo Selezionato</source>
        <translation>Profile Action</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="212"/>
        <source>Crea profilo da mondo Minecraft</source>
        <translation>Create profile from Minecraft world</translation>
    </message>
    <message>
        <location filename="game_saver_gui.py" line="234"/>
        <location filename="game_saver_gui.py" line="346"/>
        <source>Azioni Generali</source>
        <translation>General Action</translation>
    </message>
</context>
<context>
    <name>MinecraftWorldsDialog</name>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="25"/>
        <source>Seleziona Mondo Minecraft</source>
        <translation>Select Minecraft World</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="31"/>
        <source>Seleziona il mondo per cui creare un profilo:</source>
        <translation>Select the world for which to create a profile:</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="38"/>
        <source>Nessun mondo trovato nella cartella &apos;saves&apos; di Minecraft.
Verifica che Minecraft Java Edition sia installato correttamente.</source>
        <translation>No world found in Minecraft &apos;saves&apos; folder.
Verify that Minecraft Java Edition is installed correctly.</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="87"/>
        <source>Errore Selezione</source>
        <translation>Error Selection</translation>
    </message>
    <message>
        <location filename="dialogs/minecraft_dialog.py" line="87"/>
        <source>Impossibile recuperare i dati del mondo selezionato.</source>
        <translation>Unable to retrieve data from the selected world.</translation>
    </message>
</context>
<context>
    <name>SettingsDialog</name>
    <message>
        <location filename="dialogs/settings_dialog.py" line="26"/>
        <location filename="dialogs/settings_dialog.py" line="143"/>
        <source>Impostazioni Applicazione</source>
        <translation>Application Settings</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="36"/>
        <location filename="dialogs/settings_dialog.py" line="144"/>
        <source>Percorso Base Backup</source>
        <translation>Basic Backup Path</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="156"/>
        <source>Standard (Consigliato)</source>
        <translation>Standard (Recommended)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="157"/>
        <source>Massima (Più Lento)</source>
        <translation>Maximum (Slowest)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="160"/>
        <source>Nessuna (Più Veloce)</source>
        <translation>None (Fastest)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="145"/>
        <source>Dimensione Massima Sorgente per Backup</source>
        <translation>Maximum Source Size for Backup</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="146"/>
        <source>Numero Massimo Backup per Profilo</source>
        <translation>Maximum Number of Backups per Profile</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="148"/>
        <source>Compressione Backup (.zip)</source>
        <translation>Backup Compression (.zip)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="149"/>
        <source>Controllo Spazio Libero Disco</source>
        <translation>Checking Disk Free Space</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="150"/>
        <source>Abilita controllo spazio prima del backup (minimo {0} GB)</source>
        <translation>Enable space check before backup (minimum {0} GB)</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="167"/>
        <source>Sfoglia...</source>
        <translation>Browse...</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="169"/>
        <source>Salva</source>
        <translation>Save</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="171"/>
        <source>Annulla</source>
        <translation>Cancel</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="185"/>
        <source>Seleziona Cartella Base per i Backup</source>
        <translation>Unable to load the translation file for English ({0}).
The interface will remain in Italian.Select Base Folder for Backups</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="209"/>
        <source>Errore Interno</source>
        <translation>Internal Error</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="209"/>
        <source>Impossibile validare il percorso.</source>
        <translation>Unable to load the translation file for English ({0}).
The interface will remain in Italian.SelectCannot validate path.ona Base Folder for Backups.</translation>
    </message>
    <message>
        <location filename="dialogs/settings_dialog.py" line="213"/>
        <source>Impostazioni</source>
        <translation>Settings</translation>
    </message>
</context>
<context>
    <name>SteamDialog</name>
    <message>
        <location filename="dialogs/steam_dialog.py" line="48"/>
        <source>Searching for Steam installation...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="51"/>
        <source>Error: Steam installation not found.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="52"/>
        <source>Searching for Steam libraries...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="55"/>
        <source>Error: No Steam libraries found.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="56"/>
        <source>Scanning installed games...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="59"/>
        <source>Searching for Steam user data...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="64"/>
        <source>Found {0} games. Ready.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="135"/>
        <source>Selezione Profilo Steam</source>
        <translation>Steam Profile Selection</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="136"/>
        <source>Trovati multipli profili Steam.
Seleziona quello corretto (di solito il più recente):</source>
        <translation>Found multiple Steam profiles.
Select the correct one (usually the most recent):</translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="153"/>
        <source>Error selecting profile.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="156"/>
        <source>Configuration cancelled (no profile selected).</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="160"/>
        <source>Configuration cancelled (empty profile selection?).</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="162"/>
        <source>Searching path for &apos;{0}&apos;...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="173"/>
        <source>Found {0} possible paths.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="196"/>
        <location filename="dialogs/steam_dialog.py" line="208"/>
        <source>Configuration cancelled.</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="205"/>
        <source>Configuration cancelled (invalid manual path).</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="214"/>
        <source>Profile &apos;{0}&apos; configured with path: {1}</source>
        <translation></translation>
    </message>
    <message>
        <location filename="dialogs/steam_dialog.py" line="220"/>
        <source>Error saving profiles.</source>
        <translation></translation>
    </message>
    <message>
        <source>Errore selezione profilo.</source>
        <translation type="vanished">Profile selection error.</translation>
    </message>
    <message>
        <source>Configurazione annullata (nessun profilo selezionato).</source>
        <translation type="vanished">Configuration cancelled (no profile selected).</translation>
    </message>
    <message>
        <source>Configurazione annullata (selezione profilo vuota?).</source>
        <translation type="vanished">Configuration cancelled (empty profile selection?).</translation>
    </message>
</context>
</TS>
